CREATE DATABASE Rental_system

USE Rental_system

CREATE TABLE Vehicles
(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	QrCode NVARCHAR(19) NOT NULL,
	Type_Transport NVARCHAR(30) NOT NULL,
	Status INT NOT NULL FOREIGN KEY REFERENCES Status(id)
)


CREATE TABLE Users
(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	Name NVARCHAR(50) NOT NULL,
	Family_Name NVARCHAR(50) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	Wallet INT NOT NULL FOREIGN KEY REFERENCES Wallets(id)
)

CREATE TABLE Rentals
(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	UserId INT NOT NULL FOREIGN KEY REFERENCES Users(id),
	Start_trip DATETIME NOT NULL,
	End_trip DATETIME NOT NULL,
	Parking_zone INT NOT NULL FOREIGN KEY REFERENCES Parking_zones(id),
	Vehicle INT NOT NULL FOREIGN KEY REFERENCES Vehicles(id)
)

CREATE TABLE Status
(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	Type_status NVARCHAR(30) NOT NULL,
	Description NVARCHAR(255) NOT NULL
)

CREATE TABLE Wallets
(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	Number_card DECIMAL(16,0) NOT NULL UNIQUE,
	THREE_code DECIMAL(3,0) NOT NULL,
	Validity DATE NOT NULL
)

CREATE TABLE Parking_Zones
(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	Width DECIMAL(8,6) NOT NULL,
	Length DECIMAL(8,6) NOT NULL,
	Approximate_address NVARCHAR(255) NOT NULL

)

